name       : netcat
version    : 0.7.1
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/netcat/netcat/0.7.1/netcat-0.7.1.tar.bz2 : b55af0bbdf5acc02d1eb6ab18da2acd77a400bafd074489003f3df09676332bb
license    : GPL-2.0
summary    : netcat - by the GNU project
description: |
    Netcat is a featured networking utility which reads and writes data across network connections, using the TCP/IP protocol. It is designed to be a reliable "back-end" tool that can be used directly or easily driven by other programs and scripts. At the same time, it is a feature-rich network debugging and exploration tool, since it can create almost any kind of connection you would need and has several interesting built-in capabilities. 
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
